Repository SuchonSite/Server, pull requests merged in 2021-11, with the labels that each got.

#37 Internal api
  src/helpers/helper.js
  src/routes/getDataFromGov.route.js
  src/routes/people.route.js
  src/server.js
Labels: enhancement

#43 Develop
  src/helpers/database.js
  src/helpers/helper.js
  src/routes/getDataFromGov.route.js
  src/routes/people.route.js
Labels: enhancement, deployment

#45 Refactor2
  src/helpers/helper.js
  src/routes/people.route.js
Labels: documentation, enhancement

#47 Swagger API on people route
  src/routes/people.route.js
  src/server.js
Labels: documentation

#53 modified delete method in people routes
  package.json
  src/helpers/database.js
  src/routes/people.route.js
  yarn.lock
Labels: bug fix
